name: DevOps Platform CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start stack
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 20

      - name: Test app endpoint
        run: curl --fail http://localhost:5000/

      - name: Test generate endpoint
        run: curl --fail http://localhost:5000/generate || true

      - name: Show running containers
        run: docker ps

      - name: Shutdown stack
        run: docker compose down